version: "3.6"

networks:
  trashlantis:

services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    networks:
     - trashlantis
    ports:
     - "5672:5672"
     - "15672:15672"
     - "15692:15692"
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=Password12!"
    networks:
     - trashlantis
    ports:
      - 1433:1433    
